#!/usr/bin/env bash



FILE=~/.config/autostart/artemisos-welcome-app.desktop




if test -f "$FILE"; then
    rm $FILE
    python3 disable.py

else
    cp  /usr/share/applications/artemisos-welcome-app.desktop ~/.config/autostart/
    python3 enable.py

fi

pause
